# Generated by Django 5.1.3 on 2024-12-03 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0005_auto_20201209_2125'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='average_difficulty',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='average_discrimination',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='average_distractor_index',
            field=models.FloatField(default=0),
        ),
    ]
