# Generated by Django 5.1.3 on 2024-12-03 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0008_studentanswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='difficulty_index',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='discrimination_index',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='distractor_option1',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='distractor_option2',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='distractor_option3',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='distractor_option4',
            field=models.FloatField(default=0),
        ),
    ]
